import Head from "next/head";
import styles from "../styles/Home.module.css";

import { Dropbox } from "dropbox";

import Player from "../comp/player";

export default function App({ files }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Player files={files} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const DB = new Dropbox({ accessToken: process.env.token });

  const files = await DB.filesListFolder({ path: process.env.dropbox_path })
    .then((res) => res.result.entries)
    .catch(function (error) {
      console.error(error);
    });

  for (let f in files) {
    files[f].url = await DB.filesGetTemporaryLink({
      path: files[f].path_lower,
    }).then((res) => res.result.link);
  }

  return {
    props: {
      files,
    },
  };
}
